version: '3'

services:

  postgres:
    image: 'postgres:14'
    container_name: 'java-postgres'
    #ports:
    #  - 5432:5432
    environment:
      - 'POSTGRES_USER=postgres'
      - 'POSTGRES_PASSWORD=root'
      - 'POSTGRES_DB=juniordb'

  app:
    build: ./
    container_name: 'java-app'
    ports:
      - 8080:8080
